name: Deploy RG with Bicep

on:
  workflow_dispatch:
    inputs:
      rgName:
        description: Name of the Resource Group
        required: true
        type: string
      location:
        description: Azure region
        required: true
        type: choice
        options:
          - centralindia
          - eastus
          - westeurope
          - southeastasia
  push:
    branches: [ main ]
    paths:
      - infra/**

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy subscription template
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          region: ${{ inputs.location || 'centralindia' }}
          template: infra/main.bicep
          parameters: >
            rgName=${{ inputs.rgName }}
            rgLocation=${{ inputs.location || 'centralindia' }}
            tags={'owner':'github-actions','repo':'${{ github.repository }}'}
          failOnStdErr: false
